"""Idempotent PostgreSQL schema for the governed data-platform plane.

The application keeps this migration stream separate from the SQLite workflow
store so a cutover of canonical data can be verified independently.
"""

from __future__ import annotations

import re


MIGRATIONS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("0001_governed_data_platform", (
        """CREATE TABLE IF NOT EXISTS {schema}.schema_migrations (
            id TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )""",
        """CREATE TABLE IF NOT EXISTS {schema}.data_contracts (
            id TEXT NOT NULL, version TEXT NOT NULL, domain_name TEXT NOT NULL, entity_type TEXT NOT NULL,
            schema_json JSONB NOT NULL, classification TEXT NOT NULL, description TEXT NOT NULL,
            allowed_sources_json JSONB NOT NULL, status TEXT NOT NULL, owner_id TEXT NOT NULL,
            contract_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, PRIMARY KEY (id, version)
        )""",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_data_contracts_one_active ON {schema}.data_contracts(id) WHERE status = 'active'",
        "CREATE INDEX IF NOT EXISTS idx_data_contracts_catalog ON {schema}.data_contracts(status, domain_name, entity_type)",
        """CREATE TABLE IF NOT EXISTS {schema}.data_ingestion_batches (
            id TEXT PRIMARY KEY, source_system TEXT NOT NULL, contract_id TEXT NOT NULL, contract_version TEXT NOT NULL,
            organization_id TEXT NOT NULL, status TEXT NOT NULL, payload_hash TEXT NOT NULL, record_count INTEGER NOT NULL,
            accepted_count INTEGER NOT NULL, rejected_count INTEGER NOT NULL, submitted_by TEXT NOT NULL,
            submitted_at TIMESTAMPTZ NOT NULL, finalized_at TIMESTAMPTZ NOT NULL
        )""",
        "CREATE INDEX IF NOT EXISTS idx_data_batches_contract ON {schema}.data_ingestion_batches(contract_id, submitted_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_data_batches_organization ON {schema}.data_ingestion_batches(organization_id, submitted_at DESC)",
        """CREATE TABLE IF NOT EXISTS {schema}.data_quality_results (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, batch_id TEXT NOT NULL, rule_code TEXT NOT NULL,
            severity TEXT NOT NULL, passed BOOLEAN NOT NULL, affected_records INTEGER NOT NULL,
            detail_json JSONB NOT NULL, executed_at TIMESTAMPTZ NOT NULL
        )""",
        "CREATE INDEX IF NOT EXISTS idx_data_quality_batch ON {schema}.data_quality_results(batch_id, id)",
        """CREATE TABLE IF NOT EXISTS {schema}.data_records (
            id TEXT PRIMARY KEY, batch_id TEXT NOT NULL, organization_id TEXT NOT NULL, entity_type TEXT NOT NULL,
            business_key TEXT NOT NULL, record_json JSONB NOT NULL, record_hash TEXT NOT NULL,
            classification TEXT NOT NULL, is_current BOOLEAN NOT NULL DEFAULT TRUE, ingested_at TIMESTAMPTZ NOT NULL
        )""",
        "CREATE INDEX IF NOT EXISTS idx_data_records_current ON {schema}.data_records(organization_id, entity_type, business_key, is_current)",
        "CREATE INDEX IF NOT EXISTS idx_data_records_batch ON {schema}.data_records(batch_id)",
        """CREATE TABLE IF NOT EXISTS {schema}.data_lineage_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, batch_id TEXT NOT NULL, event_type TEXT NOT NULL,
            source_system TEXT NOT NULL, target_dataset TEXT NOT NULL, contract_id TEXT NOT NULL,
            contract_version TEXT NOT NULL, payload_hash TEXT NOT NULL, record_count INTEGER NOT NULL,
            actor_id TEXT NOT NULL, occurred_at TIMESTAMPTZ NOT NULL, prev_hash TEXT NOT NULL, event_hash TEXT NOT NULL
        )""",
        "CREATE INDEX IF NOT EXISTS idx_data_lineage_hash ON {schema}.data_lineage_events(event_hash)",
        "CREATE INDEX IF NOT EXISTS idx_data_lineage_batch ON {schema}.data_lineage_events(batch_id, id)",
        """CREATE TABLE IF NOT EXISTS {schema}.cutover_receipts (
            source_fingerprint TEXT PRIMARY KEY, source_label TEXT NOT NULL, manifest_json JSONB NOT NULL,
            migrated_by TEXT NOT NULL, migrated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )""",
    )),
)


def quote_schema(schema: str) -> str:
    if not re.fullmatch(r"[a-z_][a-z0-9_]{0,62}", schema):
        raise ValueError("PostgreSQL schema 标识不安全")
    return f'"{schema}"'


def apply_migrations(connection, schema: str) -> list[str]:
    quoted = quote_schema(schema)
    connection.execute(f"CREATE SCHEMA IF NOT EXISTS {quoted}")
    connection.execute(f"CREATE TABLE IF NOT EXISTS {quoted}.schema_migrations (id TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)")
    rows = connection.execute(f"SELECT id FROM {quoted}.schema_migrations").fetchall()
    applied = {row["id"] if isinstance(row, dict) else row[0] for row in rows}
    executed: list[str] = []
    for migration_id, statements in MIGRATIONS:
        if migration_id in applied:
            continue
        for statement in statements:
            connection.execute(statement.format(schema=quoted))
        connection.execute(f"INSERT INTO {quoted}.schema_migrations(id) VALUES (%s)", (migration_id,))
        executed.append(migration_id)
    return executed
